In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf

In [2]:
sess = tf.InteractiveSession()
###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
# Hint: look up tf.cond()
# I do the first problem for you
###############################################################################

x = tf.random_uniform([]) 
y = tf.random_uniform([])
out = tf.cond(tf.greater(x,y), lambda: tf.add(x,y), lambda: tf.subtract(x,y))
print ('x=', sess.run(x))
print ('y=', sess.run(y))
print(sess.run(out))

x= 0.471451
y= 0.943321
-0.26547


In [3]:
###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from the range [-1, 1).
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################

x = tf.random_uniform([], minval=-1, maxval=1, dtype=tf.float32)
y = tf.random_uniform([], minval=-1, maxval=1, dtype=tf.float32)
print(sess.run(x))
print(sess.run(y))

out = tf.case({tf.less(x, y): lambda: tf.add(x, y), 
               tf.greater(x, y): lambda: tf.subtract(x, y)},
              default=lambda: tf.constant(0.0), exclusive=True)
sess = tf.InteractiveSession()
print(sess.run(out))

0.931075
-0.659994
1.6352


In [4]:
##############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################

x = tf.constant([[0, -2, -1], [0, 1, 2]])
print(sess.run(x))
y = tf.zeros_like(x)
print(sess.run(y))
out = tf.equal(x, y)
print(sess.run(out))

[[ 0 -2 -1]
 [ 0  1  2]]
[[0 0 0]
 [0 0 0]]
[[ True False False]
 [ True False False]]


In [5]:
###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################
x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
                 30.97266006,  26.67541885,  38.08450317,  20.74983215,
                 34.94445419,  34.45999146,  29.06485367,  36.01657104,
                 27.88236427,  20.56035233,  30.20379066,  29.51215172,
                 33.71149445,  28.59134293,  36.05556488,  28.66994858])
print(sess.run(x))
indices = tf.where(x>30)
out = tf.gather(x, indices)
print(sess.run(out))

[ 29.05088806  27.61298943  31.19073486  29.35532951  30.97266006
  26.67541885  38.08450317  20.74983215  34.94445419  34.45999146
  29.06485367  36.01657104  27.88236427  20.56035233  30.20379066
  29.51215172  33.71149445  28.59134293  36.05556488  28.66994858]
[[ 31.19073486]
 [ 30.97266006]
 [ 38.08450317]
 [ 34.94445419]
 [ 34.45999146]
 [ 36.01657104]
 [ 30.20379066]
 [ 33.71149445]
 [ 36.05556488]]


In [6]:
###############################################################################
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
###############################################################################
out = tf.diag(tf.range(1,7))
print(sess.run(out))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [7]:
###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################
x = tf.random_normal([10,10], mean = 10, stddev=1)
print(sess.run(x))
out = tf.matrix_determinant(x)
print(sess.run(out))

[[  9.72965145   9.7093277   10.62124538   9.02892208  10.07095814
   10.66601562  10.38462257   9.33609581   9.96628857   8.68644524]
 [ 10.57400608  10.10367393  11.00842285   9.73651505  10.57184219
   11.49061298  11.09778786   8.74654579  10.34562016   9.84796143]
 [ 11.0514431   10.41993999  12.14727497   9.16931343  10.39657879
   10.24847031   9.21901035  10.9651947    7.68309069  11.139575  ]
 [ 11.01603889   8.02983379   9.47463512   8.93791771   9.87714195
    8.53229713  10.83100891   8.95640755  10.39154148  11.49610519]
 [ 10.31473637   7.9414587   11.48801041   9.97298813   9.48463535
   10.38898754  10.29345608   9.46201897  12.21740437  10.17730904]
 [  8.99314404   9.62834644   9.71775436   9.93022537   8.92694473
   11.65139866   8.50200939  10.17599869   9.76196003  10.05492687]
 [  8.6574707   11.68047523   9.42784405  10.86350822  10.05910587
    9.64007664  10.8433876   10.3379097    8.89284897   9.7027092 ]
 [  8.73630905   9.72544098  10.38897896   9.60347843  

In [8]:
###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
print(sess.run(x))
unique, idx = tf.unique(x)
print(sess.run(unique))

[ 5  2  3  5 10  6  2  3  4  2  1  1  0  9]
[ 5  2  3 10  6  4  1  0  9]


In [9]:
###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.cond() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################
x = tf.random_normal([300], mean = 5, stddev=1)
y = tf.random_normal([300], mean = 5, stddev=1)

average = tf.reduce_mean(x-y)
print('average=', sess.run(average))
def f1(): return tf.reduce_mean(tf.square(x-y))
def f2(): return tf.reduce_sum(tf.abs(x-y))

out = tf.cond(average < 0, f1, f2 )
print('out=', sess.run(out))

average= -0.100807
out= 366.913
